export const MODEL_LABELS: Record<string, string> = {
  'llama-3.3-70b-versatile':                  'Llama 3.3 70B',
  'llama-3.1-8b-instant':                     'Llama 3.1 8B Instant',
  'llama3-70b-8192':                           'Llama 3 70B',
  'mixtral-8x7b-32768':                        'Mixtral 8x7B',
  'gemma2-9b-it':                              'Gemma 2 9B',
  'qwen-2.5-72b':                              'Qwen 2.5 72B',
  'claude-3-5-sonnet-20241022':                'Claude 3.5 Sonnet',
  'claude-3-5-haiku-20241022':                 'Claude 3.5 Haiku',
  'claude-3-opus-20240229':                    'Claude 3 Opus',
  'claude-3-haiku-20240307':                   'Claude 3 Haiku',
  'gemini-2.0-flash':                          'Gemini 2.0 Flash',
  'gemini-1.5-pro':                            'Gemini 1.5 Pro',
  'gemini-1.5-flash':                          'Gemini 1.5 Flash',
  'gemini-2.0-flash-thinking-exp':             'Gemini 2.0 Flash Thinking',
  'gpt-4o':                                    'GPT-4o',
  'gpt-4o-mini':                               'GPT-4o Mini',
  'gpt-4-turbo':                               'GPT-4 Turbo',
  'gpt-3.5-turbo':                             'GPT-3.5 Turbo',
  'o1':                                        'o1',
  'o1-mini':                                   'o1 Mini',
  'o3-mini':                                   'o3 Mini',
  'deepseek-chat':                             'DeepSeek V3',
  'deepseek-reasoner':                         'DeepSeek R1 (Thinking)',
  'mistral-large-latest':                      'Mistral Large',
  'mistral-small-latest':                      'Mistral Small',
  'codestral-latest':                          'Codestral',
  'open-mistral-nemo':                         'Mistral Nemo',
  'grok-2-latest':                             'Grok 2',
  'grok-2-vision-latest':                      'Grok 2 Vision',
  'grok-beta':                                 'Grok Beta',
  'sonar-pro':                                 'Sonar Pro',
  'sonar':                                     'Sonar',
  'sonar-reasoning-pro':                       'Sonar Reasoning Pro',
  'meta-llama/Llama-3.3-70B-Instruct-Turbo':  'Llama 3.3 70B Turbo',
  'deepseek-ai/DeepSeek-V3':                   'DeepSeek V3',
  'Qwen/Qwen2.5-72B-Instruct-Turbo':          'Qwen 2.5 72B Turbo',
  'mistralai/Mixtral-8x22B-Instruct-v0.1':    'Mixtral 8x22B',
  'command-r-plus-08-2024':                    'Command R+',
  'command-r-08-2024':                         'Command R',
  'command-light':                             'Command Light',
  'gemma3':                                    'Gemma 3',
  'gemma2':                                    'Gemma 2',
  'llama3.2':                                  'Llama 3.2',
  'llama3.1':                                  'Llama 3.1',
  'codellama':                                 'Code Llama',
  'deepseek-coder-v2':                         'DeepSeek Coder V2',
  'qwen2.5-coder':                             'Qwen 2.5 Coder',
  'phi3':                                      'Phi 3',
  'mistral':                                   'Mistral 7B',
  'starcoder2':                                'StarCoder 2',
}

export function label(modelId: string): string {
  return MODEL_LABELS[modelId] ?? modelId
}
